# Generated by Django 5.0 on 2023-12-16 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='average_score',
            field=models.FloatField(default=0),
        ),
    ]
