# Generated by Django 5.0 on 2023-12-20 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_reviewvote'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
