# Generated by Django 4.2.6 on 2023-12-18 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_book_average_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='display_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
